server:
  port: 8989

eureka:
  client:
    registryFetchIntervalSeconds: 5

ribbon:
  IsSecure: false

workshop:
  ribbon:
    ServerListRefreshInterval: 5000

security:
  basic:
    enabled: false

management:
  security:
    enabled: false


---

spring:
  profiles: pact

ribbon:
  eureka:
    enabled: false

hystrix:
  command:
    randomFortune:
      execution.isolation.thread.timeoutInMilliseconds: 2000

workshop:
  ribbon:
    listOfServers: localhost:8007
   
  
      
        
    
